version: '3'
services:
  laravel:
    image: composer:2
    volumes:
      - ./laravel:/var/www
    working_dir: /var/www
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
  frontend:
    image: node:14
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run serve
    ports:
      - "8080:8080"
    depends_on:
      - laravel
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: laravel_vue_tutorial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

